/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false server/cloudflare-env.d.ts` (hash: 9cc2bfaaf1a625480708afda92bdc54c)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../.output/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
